[package]
name = "roblox_counter_blox_multi"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = "0.9.0"
gdk = "0.9.0"
glade = "0.9.0"
rand = "0.8.5"
reqwest = { version = "0.11", features = ["blocking", "json"] }

[profile.release]
opt-level = 3